### ISSUE TITLE
Level may crash when rendering a release sound?

### ISSUE THREAD

**Issue by AverageMaipuperson** [clicksounds/geode-clicksound#22]
When i play and go through a lot of attempts, for some reason, one time when i release the game randomly crashes, and i didnt find anything important in the crash logs except common messages that appear in every crash, most of the time it happens when restarting the level when a release sound seems to sound for some reason

**Comment by BeatACVR** [comment]
that is your personal problem. 👍

**Comment by AverageMaipuperson** [comment]
> that is your personal problem. 👍

**Comment by AverageMaipuperson** [comment]
> that is your personal problem. 👍

In which way? You're not even explaining the actual problem bruh 😭🙏

**Comment by BeatACVR** [comment]
what platform

**Comment by AverageMaipuperson** [comment]
> what platform

android

**Comment by BeatACVR** [comment]
> > what platform
> android

android has issues
that is your own personal problem 👍

**Comment by coopeeo** [comment]
stale
